---
- name: Define php_fpm_daemon.
  set_fact:
    php_fpm_daemon: "{{ __php_fpm_daemon }}"
  when: php_fpm_daemon is not defined

- name: Define php_fpm_pool_conf_path.
  set_fact:
    php_fpm_pool_conf_path: "{{ __php_fpm_pool_conf_path }}"
  when: php_fpm_pool_conf_path is not defined

- name: Define php_fpm_pool_conf_dir.
  set_fact:
    php_fpm_pool_conf_dir: "{{ php_fpm_pool_conf_path | dirname }}"
  when: php_fpm_pool_conf_dir is not defined

- name: Ensure the default pool directory exists.
  file:
    path: "{{ php_fpm_pool_conf_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Define php_fpm_noname_pool_conf_path.
  set_fact:
    php_fpm_noname_pool_conf_path: "{{ php_fpm_pool_conf_dir }}/_.default"
  when: php_fpm_noname_pool_conf_path is not defined

- name: Define php_fpm_noname_pool_info
  stat: path={{ php_fpm_noname_pool_conf_path }}
  register: php_fpm_noname_pool_info

- name: Ensure the default pool exists.
  copy:
    src: www.conf
    dest: "{{ php_fpm_pool_conf_path }}"
    owner: root
    group: root
    mode: 0644
    force: no
  when: php_fpm_noname_pool_info.stat.exists == false

- name: Rename default pool.
  command: mv -n {{ php_fpm_pool_conf_path }} {{ php_fpm_noname_pool_conf_path }}
  when: php_enable_php_fpm and (php_fpm_noname_pool_info.stat.exists == false)
  notify: restart php-fpm

- name: Define php_fpm_custom_pool_conf.
  shell: >
    find . -type f -iname '*.conf'
    chdir={{ php_fpm_pool_conf_dir }}
  register: php_fpm_custom_pool_conf
  when: php_enable_php_fpm
  changed_when: false

# Idempotence test: fail
- name: Remove custom pool.
  file: path={{ php_fpm_pool_conf_dir }}/{{ item }} state=absent
  # https://github.com/ansible/ansible/issues/13274
  with_items: "{{ php_fpm_custom_pool_conf.stdout_lines|default([]) }}"
  when: php_enable_php_fpm or (php_fpm_pools|length == 0)
  notify: restart php-fpm

- name: Ensure the custom pool exists.
  shell: >
    cp -n {{ php_fpm_noname_pool_conf_path }} {{ item.name }}.conf
    chdir={{ php_fpm_pool_conf_dir }}
    creates={{ item.name }}.conf
  with_items: "{{ php_fpm_pools }}"
  when: php_enable_php_fpm and (php_fpm_pools|length > 0)
  notify: restart php-fpm

- include: configure-fpm-pool.yml
  when: php_enable_php_fpm and (php_fpm_pools|length > 0)
  notify: restart php-fpm

- name: Ensure php-fpm is started and enabled at boot (if configured).
  service: name={{ php_fpm_daemon }} state=started enabled=yes
  when: php_enable_php_fpm and (php_fpm_pools|length > 0)

- name: Ensure php-fpm is stopped and disabled at boot (if configured) (if package).
  service: name={{ php_fpm_daemon }} state=stopped enabled=no
  when: (php_enable_php_fpm == false or php_fpm_pools|length == 0) and ((php_install_from_source == false) or (php_install_from_source and "'--enable-fpm' in php_source_configure_command"))
